-- Teams represent randomized groups of users (typically size 3).
create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

-- Profiles are linked 1:1 with Supabase auth.users via the same UUID.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  team_id uuid references public.teams(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Submissions capture a team’s project vibe-check and AI evaluation.
create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  created_by uuid references public.profiles(id),
  project_name text not null,
  project_description text not null,
  ai_questions jsonb, -- three project-specific questions generated by Gemini
  ai_score numeric(5,2), -- 0–100 score with optional decimals
  ai_verdict text, -- one-paragraph professional but witty feedback
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


